version: '3'
services:
  db:
    build: ./mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  db-store: