@startuml
' hide the spot
hide circle

'avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as users {
  +id : number
  name: text
  email: text
}

entity "projects" as projects {
  +id : number,
  name: text,
  content: text,
  --
  user_id: text
}

entity "user_project" as user_project {
  +id : number,
  user_role: text,
  --
  #user_id: number,
  #project_id: number,
}

entity "user_directory" as user_directory {
  +id : number
  user_role: text
  --
  #user_id : number
  #directory_id : number
}

entity "directories" as directories {
  +id : number
  author_name: text
  directory_name: text
  content: text
  edited_date: date
  --
  #project_id: number
  #user_directory_id
}

entity "directory_path" as directory_path {
  +id:number,
  --
  #parent_directory_id: number,
  #child_directory_id: number,
}

entity "documents" as documents {
  +id : number
  content: text
  --
  #user_id: number
  #directory_id: number
}

entity "document_histories" as document_histories {
  +id : number
  user_id: number
  previous_content: text
  edited_content: text
  edited_date
}

users ||..o{ user_project
users ||..o{ user_directory
users ||..o{ documents
user_project ||..o{ projects
user_directory ||..o{ directories
projects ||..o{ directories
directories ||..o{ directory_path
directories ||..o{ documents
documents ||..o{ document_histories
@enduml