@startuml

/'
  Assignee
  Issue
  Assignee_to
'/
entity "Assignee" {
  id [PK]
  --
  name
}

entity "Issue" {
  id [PK]
  --
  name
}

entity "Assignee_to" {
  id [PK]
  --
  name
}

/'
関係性
------   :1
----||   :1 and only 1
----o|   :0 or 1
-----{   :many
----|{   :1 or more
----o{   :0 or many

entityの位置
ri ...right
le ...left
do ...down
'/

Assignee ||..o{ Issue
Issue ||..o{ Assignee_to
@enduml